import Head from "next/head";
import { HomeTemplate, HomeTemplateProps } from "src/templates/Home";
import { GetStaticProps } from "next";
import { service } from "src/services/api";

export default function Home(props: HomeTemplateProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeTemplate {...props} />
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const teams = await service.getTeams();

  return { props: { teams } };
};
